services:
  - type: web
    name: gestion-compra-web
    env: node
    plan: starter
    buildCommand: npm install && npx playwright install chromium && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "0"
